### ISSUE TITLE
No squeak?

### ISSUE THREAD

**Issue by burner1024** [FredrikLindgren/randomiser#1]
I'm using v7 on BGT. It appears that there's no squeak (tried BG1 and ToB start).
With LStest, I can see a flurry of fl* scripts run at first, then they stop.
Is there still supposed to be a squeak? If yes, how do I debug this further?
![Captura de pantalla de 2021-09-20 17-57-16](https://user-images.githubusercontent.com/1279852/133991624-1751f23e-f919-4dee-bcd4-7966bd87246f.png)

**Comment by burner1024** [comment]
Found and uncommented some debug options in the scripts:
![Captura de pantalla de 2021-09-22 10-01-29](https://user-images.githubusercontent.com/1279852/134276820-6f888b3d-80b1-4d5c-90fc-fbd6e7dc1bc4.png)
![Captura de pantalla de 2021-09-22 10-01-36](https://user-images.githubusercontent.com/1279852/134276825-22507d72-b0f4-4145-b69f-776486f9ee17.png)

Not sure why `fltiersa` keeps messaging after `sa` tier is done, could be out of order due to action queue?
But block 887 of `fltiersc` is 
```
IF
	Global("flsctDone","GLOBAL",1)
THEN
	RESPONSE #100
		ActionOverride(Player1,DisplayStringHead(Myself,762101))  // Running block 887 of FLTIERSC.BCS
		DestroySelf()
END
```

Strange how it's run 3 times, that might mean that there's multiple cres with that script?

The installed option is `Randomise items -> Mode 1: Randomise with in-game scripts. Some items are lost: 7`

**Comment by burner1024** [comment]
Turns out I somehow screwed up my `linux.ini`... Once fixed and reinstalled, squeak is back!

**Comment by FredrikLindgren** [comment]
Glad it worked out for you. I'm fairly certain the reason you saw the DestroySelf() block run multiple times is because the randomisation scripts run several in parallel, since the process is quite slow. I.e., there is some algorithmically determined number of copies of the same randomisation critter sitting side-by-side and once they are done, they all go poof.
