### ISSUE TITLE
Issue with randomising into the Demon Lord reward

### ISSUE THREAD

**Issue by basicals** [FredrikLindgren/randomiser#5]
The option to offer the dragon eggs to the demon is locked to evil players only, this means that randomising items into it literally blocks them for good or neutral runs.

I've just had to extract Daystar from him with EEKeeper because of this lol.

![image](https://github.com/FredrikLindgren/randomiser/assets/6373803/85819402-8359-4ca3-aa06-98e12ae913d4)

**Comment by FredrikLindgren** [comment]
The same item awarded by the demon is also awarded by Adalon for returning the eggs.
